"""
TestSentinelSentinel - Auto-generated by Starlight Visual Editor
Automatically dismisses cookie consent banners
"""

import asyncio
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sdk.starlight_sdk import SentinelBase


class TestSentinelSentinel(SentinelBase):
    def __init__(self):
        super().__init__(layer_name="TestSentinelSentinel", priority=3)
        self.selectors = [".cookie-banner","#cookie-consent","[data-cookie]",".cc-banner"]
        self.capabilities = ["popup-detection"]

    async def on_pre_check(self, params, msg_id):
        blocking = params.get("blocking", [])
        
        # Check for matching patterns
        matches = [b for b in blocking 
                   if any(s in b.get("selector", "") for s in self.selectors)]
        
        if matches:
            print(f"[{self.layer}] Pattern detected: {len(matches)} match(es)")
            await self.send_hijack("Obstacle blocking execution")
            
            # Click the dismiss button
            for sel in [".accept-btn","#accept-cookies","[data-accept]"]:
                await self.send_action("click", sel)
            
            await self.send_resume()
        else:
            await self.send_clear()


if __name__ == "__main__":
    sentinel = TestSentinelSentinel()
    asyncio.run(sentinel.start())
